openapi: 3.1.0
info:
  title: Backoffice endpoints for Booking app
  description: Backoffice endpoints for Booking app
  version: 1.0.0
paths:
  /barbershops:
    get:
      tags:
        - Barbershop
      summary: List of all barbershops
      operationId: getAllBarbershops
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BarbershopInfo'

components:
  schemas:
    BarbershopInfo:
      type: object
      required:
        - id
        - name
        - address
        - opensAt
        - closesAt
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/AddressInfo'
        opensAt:
          type: integer
          format: int64
        closesAt:
          type: integer
          format: int64

    AddressInfo:
      type: object
      required:
        - id
        - region
        - city
        - street
      properties:
        id:
          type: string
        region:
          type: string
        city:
          type: string
        street:
          type: string


  
